# This file was auto-generated by Polybuild

ifndef OS
	OS := $(shell uname)
	export OS
endif

ifeq ($(OS),Windows_NT)
	CC := cl
	CXX := cl
	CL := /nologo
	MSYS_NO_PATHCONV := 1
	export CC CXX CL MSYS_NO_PATHCONV
endif

all: prelude0 prelude1
	@"$(MAKE)" -f .polybuild.mk --no-print-directory
.PHONY: all

prelude0:
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Executing prelude:  cd fltk && cmake . -B build -G \"Unix Makefiles\" -DCMAKE_BUILD_TYPE=Release -DFLTK_BUILD_TEST=OFF && \"$(MAKE)\" -C build "
	@ cd fltk && cmake . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DFLTK_BUILD_TEST=OFF && "$(MAKE)" -C build 
.PHONY: prelude0

prelude1:
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Executing prelude:  cd libdatachannel && cmake -B build -G \"Unix Makefiles\" -DCMAKE_BUILD_TYPE=Release -DCMAKE_POLICY_VERSION_MINIMUM=3.5 && \"$(MAKE)\" -C build datachannel-static "
	@ cd libdatachannel && cmake -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_POLICY_VERSION_MINIMUM=3.5 && "$(MAKE)" -C build datachannel-static 
.PHONY: prelude1

clean:
	@"$(MAKE)" -f .polybuild.mk --no-print-directory $@
.PHONY: clean

install:
	@"$(MAKE)" -f .polybuild.mk --no-print-directory $@
.PHONY: install
