[paths]
output = "lux-desktop"
source = [".", "Polyweb", "Polyweb/Polynet"]
include = ["fltk", "libdatachannel/include"]
artifact = "obj"
install = "/usr/local/bin"

[options]
compilation-flags = "-Wall -std=c++17 -Ifltk/build -DRTC_STATIC -O3 -march=native -mtune=native -pthread"
link-time-flags = "`fltk/build/fltk-config --ldstaticflags`"
libraries = ["ssl", "crypto"]
static-libraries = [
    "libdatachannel/build/libdatachannel-static.a",
    "libdatachannel/build/deps/libjuice/libjuice-static.a",
    "libdatachannel/build/deps/libsrtp/libsrtp2.a",
    "libdatachannel/build/deps/usrsctp/usrsctplib/libusrsctp.a",
]
pkg-config-libraries = ["sdl2", "gstreamer-video-1.0", "gstreamer-app-1.0", "gstreamer-1.0", "nice", "gio-2.0"]
preludes = [
    """ \
        cd fltk && \
        cmake . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DFLTK_BUILD_TEST=OFF && \
        "$(MAKE)" -C build \
    """,
    """ \
        cd libdatachannel && \
        cmake -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_POLICY_VERSION_MINIMUM=3.5 && \
        "$(MAKE)" -C build datachannel-static \
    """,
]
clean-preludes = ["rm -rf fltk/build", "rm -rf libdatachannel/build"]

[env.OS.Windows_NT.options]
compilation-flags = "/W4 /std:c++17 /EHsc /Ifltk/build /DRTC_STATIC /Ox /arch:native"
libraries = ["ssl", "crypto", "ws2_32", "iphlpapi"]
static-libraries = [
    "libdatachannel/build/datachannel-static.lib",
    "libdatachannel/build/deps/libjuice/juice-static.lib",
    "libdatachannel/build/deps/libsrtp/srtp2.lib",
    "libdatachannel/build/deps/usrsctp/usrsctplib/usrsctp.lib",
]
