#!/bin/bash
# This file was auto-generated by Polybuild

if [[ ! " $* " =~ [[:space:]](clean|install)[[:space:]] ]]; then
	printf "\033[1m[POLYBUILD]\033[0m %s\n" "Executing prelude:  cd fltk && cmake . -B build -DCMAKE_BUILD_TYPE=Release -DFLTK_BUILD_TEST=OFF && cmake --build build "
	 sh -c " cd fltk && cmake . -B build -DCMAKE_BUILD_TYPE=Release -DFLTK_BUILD_TEST=OFF && cmake --build build "
	printf "\033[1m[POLYBUILD]\033[0m %s\n" "Executing prelude:  cd libdatachannel && cmake -B build -G \"Unix Makefiles\" -DCMAKE_BUILD_TYPE=Release -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DUSE_NICE=1 && cd build && make datachannel-static "
	 sh -c " cd libdatachannel && cmake -B build -G \"Unix Makefiles\" -DCMAKE_BUILD_TYPE=Release -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DUSE_NICE=1 && cd build && make datachannel-static "
fi

make -f .polybuild.mk "$@"
